development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:0767af21b25cfee3ce97e2fef09c065e@scat.redistogo.com:11195/
  channel_prefix: bygone_note_production
